
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."drivers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "full_name" character varying DEFAULT ''::character varying NOT NULL,
    "freetext_notes" "text" DEFAULT ''::"text" NOT NULL,
    "year_of_racing" integer
);

ALTER TABLE "public"."drivers" OWNER TO "postgres";

ALTER TABLE "public"."drivers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."drivers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."drivers"
    ADD CONSTRAINT "drivers_pkey" PRIMARY KEY ("id");

CREATE POLICY "Enable select for authenticated users only" ON "public"."drivers" AS PERMISSIVE for SELECT to authenticated using (true);

ALTER TABLE "public"."drivers" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."drivers" TO "anon";
GRANT ALL ON TABLE "public"."drivers" TO "authenticated";
GRANT ALL ON TABLE "public"."drivers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."drivers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."drivers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."drivers_id_seq" TO "service_role";

RESET ALL;
